export const disabilityTypes = {
  CHANGE_DISABILITY_STATE: 'CHANGE_DISABILITY_STATE',
  RESET_DISABILITY_STATE: 'RESET_DISABILITY_STATE',
};

export const loadingTypes = {
  SET_LOADING: 'SET_LOADING',
  SET_NOT_LOADING: 'SET_NOT_LOADING',
};
