export const disabilityTypes = {
  CHANGE_DISABILITY_STATE: 'CHANGE_DISABILITY_STATE',
  RESET_DISABILITY_STATE: 'RESET_DISABILITY_STATE',
};

export const loadingTypes = {
  SET_LOADING: 'SET_LOADING',
  SET_NOT_LOADING: 'SET_NOT_LOADING',
};

export const appTypes = {
  SET_APP_STATE: 'SET_APP_STATE',
  SET_USER: 'SET_USER',
  LOGOUT_USER: 'LOGOUT_USER',
  LOGIN_USER: 'LOGIN_USER',
  REFRESH_USER: 'REFRESH_USER',
};

export const contentTypes = {
  SET_CONTENT_SUCCESS: 'SET_CONTENT_SUCCESS',
  SET_CONTENT_FAILED: 'SET_CONTENT_FAILED',
  LOAD_CONTENT: 'LOAD_CONTENT',
  CREATE_CONTENT: 'CREATE_CONTENT',
  UPDATE_CONTENT: 'UPDATE_CONTENT',
  DELETE_CONTENT: 'DELETE_CONTENT',
  SET_ACTIVE: 'SET_ACTIVE',
};

export const usersTypes = {
  LOAD_USERS_SUCCESS: 'LOAD_USERS_SUCCESS',
  LOAD_USERS_FAILED: 'LOAD_USERS_FAILED',
  LOAD_USERS: 'LOAD_USERS',
  CREATE_USER: 'CREATE_USER',
  UPDATE_USER: 'UPDATE_USER',
  DELETE_USER: 'DELETE_USER',
  SET_ADMIN: 'SET_ADMIN',
};
